import DashboardLayout from "./layout/dashboard";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <DashboardLayout>{children}</DashboardLayout>;
}
